In [2]:
import numpy as np

In [3]:
L = [1,2,3] # python list
A = np.array([1,2,3]) # numpy array

In [4]:
# Loop and print python list
for e in L:
    print(e)

1
2
3


In [5]:
# Loop and print np.array
for e in A:
    print(e)

1
2
3


In [6]:
L.append(4) # Add element to list
L

[1, 2, 3, 4]

In [7]:
A.append(4) # Try add element to np.array, result in error
A

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [8]:
L + [5] # Add element to list

[1, 2, 3, 4, 5]

In [10]:
A + np.array([4]) # Broadcasting, add 4 to each element in the np.array

array([5, 6, 7])

In [12]:
A + np.array([4, 5, 6]) # Vector addition

array([5, 7, 9])

In [13]:
A + np.array([4, 5]) # For vector operation, shape must be the same

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [14]:
2 * A # Broadcasting, multiply each element in np.array

array([2, 4, 6])

In [16]:
2 * L # Extend array but appending list by itself

[1, 2, 3, 4, 1, 2, 3, 4]

In [17]:
L + L # Add list by itself

[1, 2, 3, 4, 1, 2, 3, 4]

In [18]:
# Element wise addition
L2 = []
for e in L:
    L2.append(e + 3)
L2

[4, 5, 6, 7]

In [19]:
# Element wise additon using list comprehension
L2 = [e + 3 for e in L]
L2

[4, 5, 6, 7]

In [20]:
L **2 # Cannot sq on list

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [21]:
# Square each element in list
L2 = [e**2 for e in L]

In [22]:
L2

[1, 4, 9, 16]

In [23]:
A**2 # Square each element in np.array

array([1, 4, 9], dtype=int32)

In [24]:
np.log(A) # Log each element in np.array

array([0.        , 0.69314718, 1.09861229])

In [25]:
np.exp(A) # Exponential each element in np.array

array([ 2.71828183,  7.3890561 , 20.08553692])

In [26]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

In [27]:
a = np.array([1,2])
b = np.array([3,4])

In [28]:
# Multiply each element from each list and sum
dot = 0
for e,f in zip(a, b):
    dot += e * f
dot

11

In [29]:
# Multiple each element in list using for loop with index
dot = 0
for i in range(len(a)):
    dot += a[i] * b[i]
dot

11

In [30]:
# Vector operation
a * b

array([3, 8])

In [31]:
# Multiply each element from each list and sum
np.sum(a*b)

11

In [32]:
# Multiply each element from each list and sum
(a*b).sum()

11

In [33]:
# Dot matrix of 2 vectors
np.dot(a,b)

11

In [34]:
# Dot matrix of 2 vectors
a.dot(b)

11

In [35]:
# @ symbol is the same as .dot
a@b

11

In [36]:
# Calculate magnitude
amag = np.sqrt((a * a).sum())
amag

2.23606797749979

In [37]:
# Calculate magnitude using linalg.norm
np.linalg.norm(a)

2.23606797749979

In [40]:
# Calculate cos angle
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosangle

0.9838699100999074

In [41]:
# Calculate arc cosine
angle = np.arccos(cosangle)

In [42]:
angle

0.17985349979247847

In [43]:
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [44]:
L[0]

[1, 2]

In [46]:
L[0][1]

2

In [47]:
A = np.array(L)

In [48]:
A

array([[1, 2],
       [3, 4]])

In [49]:
A[0][1]

2

In [50]:
A[0,1]

2

In [51]:
A[:,0]

array([1, 3])

In [52]:
A.T

array([[1, 3],
       [2, 4]])

In [53]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [54]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [55]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [57]:
A.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [59]:
np.linalg.det(A)

-2.0000000000000004

In [60]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [61]:
np.linalg.inv(A).dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [62]:
np.trace(A)

5

In [63]:
A

array([[1, 2],
       [3, 4]])

In [64]:
np.diag(A)

array([1, 4])

In [65]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [66]:
Lam, V = np.linalg.eig(A)

In [67]:
Lam

array([-0.37228132,  5.37228132])

In [68]:
V

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [69]:
V[:,0] * Lam[0] == A @ V[:,0]

array([ True, False])

In [70]:
V[:,0] * Lam[0], A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [71]:
np.allclose(V[:,0] * Lam[0], A @ V[:,0])

True

In [73]:
np.allclose(V @ np.diag(Lam), A@V)

True

In [74]:
# A inv * B, use np.linalg.solve
A = np.array([[1,1],[1.5, 4]])
B = np.array([2200, 5050])

In [75]:
np.linalg.solve(A, B)

array([1500.,  700.])

In [76]:
np.linalg.inv(A).dot(B)

array([1500.,  700.])